name: Continuous Deployment on PR
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      SOURCE_DIR: './build/'
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PATHS: '/*'
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    steps:
      - uses: actions/checkout@v1 #1

      - name: Get branch name #2
        id: vars
        run: echo ::set-output name=branch::${{github.event.pull_request.head.ref}}

      - name: Install dependencies #3
        run: yarn

      - name: Build # 4
        run: export BRANCH_NAME=${{ steps.branch.outputs.branch }} && yarn build:uat
        
      - name: AWS Deploy #5
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks
        env:
          DEST_DIR: ${{steps.vars.outputs.branch}}
